/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env= --include-runtime=false --strict-vars=false` (hash: 582484a48cbf71cfdd2995c9c4c498d9)
interface __BaseEnv_Env {
	JOB_SEARCH_DB: D1Database;
	AI: Ai;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	OWNER_EMAIL: string;
	MICROSOFT_GRAPH_ENABLED: string;
	MICROSOFT_CLIENT_ID: string;
	MICROSOFT_REDIRECT_URI: string;
	HISTORICAL_START_DATE: string;
	GOOGLE_SPREADSHEET_ID: string;
	GOOGLE_SHEET_RANGE: string;
	AI_ENABLED: string;
	AI_DAILY_CALL_LIMIT: string;
	AI_MODEL: string;
	AI_GATEWAY_ID: string;
	SYNC_ENABLED: string;
	ALLOWED_ORIGIN: string;
	JOB_SYNC: Workflow<Parameters<import("./src/index").JobSyncWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		JOB_SEARCH_DB: D1Database;
		AI: Ai;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		MICROSOFT_GRAPH_ENABLED: string;
		MICROSOFT_CLIENT_ID: string;
		MICROSOFT_REDIRECT_URI: string;
		HISTORICAL_START_DATE: string;
		GOOGLE_SPREADSHEET_ID: string;
		GOOGLE_SHEET_RANGE: string;
		AI_ENABLED: string;
		AI_DAILY_CALL_LIMIT: string;
		AI_MODEL: string;
		AI_GATEWAY_ID: string;
		SYNC_ENABLED: string;
		ALLOWED_ORIGIN: string;
		JOB_SYNC: Workflow<Parameters<import("./src/index").JobSyncWorkflow['run']>[0]['payload']>;
	}
	interface ProductionEnv {
		JOB_SEARCH_DB: D1Database;
		AI: Ai;
		ACCESS_TEAM_DOMAIN: string;
		ACCESS_AUD: string;
		OWNER_EMAIL: string;
		MICROSOFT_GRAPH_ENABLED: string;
		MICROSOFT_CLIENT_ID: string;
		MICROSOFT_REDIRECT_URI: string;
		HISTORICAL_START_DATE: string;
		GOOGLE_SPREADSHEET_ID: string;
		GOOGLE_SHEET_RANGE: string;
		AI_ENABLED: string;
		AI_DAILY_CALL_LIMIT: string;
		AI_MODEL: string;
		AI_GATEWAY_ID: string;
		SYNC_ENABLED: string;
		ALLOWED_ORIGIN: string;
		JOB_SYNC: Workflow<Parameters<import("./src/index").JobSyncWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "OWNER_EMAIL" | "MICROSOFT_GRAPH_ENABLED" | "MICROSOFT_CLIENT_ID" | "MICROSOFT_REDIRECT_URI" | "HISTORICAL_START_DATE" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_RANGE" | "AI_ENABLED" | "AI_DAILY_CALL_LIMIT" | "AI_MODEL" | "AI_GATEWAY_ID" | "SYNC_ENABLED" | "ALLOWED_ORIGIN">> {}
}
